# Use Ubuntu Jammy (22.04) as base image
FROM ubuntu:jammy

# Set environment variables
# ENV NODE_VERSION=20.x

# Update package lists and install basic dependencies
RUN apt-get update && apt-get upgrade -y

# Install build essentials and common tools
RUN apt-get install -y \
    curl
    # Install Node.js and npm
# RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
#     && apt-get install -y nodejs


RUN curl -fsSL https://deb.nodesource.com/setup_22.x -o nodesource_setup.sh

RUN bash nodesource_setup.sh
RUN apt-get install -y nodejs
# Install Node.js
RUN apt-get install -y nodejs

# Verify installations
RUN node --version && npm --version

# Create app directory
WORKDIR /usr/src/app

# Copy package files
# COPY package*.json ./
# copy all the files in the present directory to this working directory
COPY . .

# Install app dependencies
# RUN npm install


# move the working directory inside smartcontract_compile folder and run npm install there and then move back to user/src/app
# WORKDIR /usr/src/app/smartcontract_compile
# RUN npm install
# WORKDIR /usr/src/app

# change working directory smartcontract_compile and make a file .env and write a value from the environment and write a value PRIVATE_KEY and set its value from the .env files PRIVATE_KEY
# RUN echo "PRIVATE_KEY=${PRIVATE_KEY}" > .env
WORKDIR /usr/src/app



# Expose port (adjust as needed)
EXPOSE 3000

# Start command (adjust as needed)
CMD ["npm", "start"]
